version: "3.8"
services: 
    postgres:
        image: postgres:13.0
        restart: never
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER:
            POSTGRES_PASSWORD:
            POSTGRES_DB: bot
        volumes: 
            - ./database-data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: "no"
        ports:
            - "8080:8080"
        depends_on:
            - "postgres"


    
